// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	repo "github.com/walkline/ToCloud9/apps/game-load-balancer/repo"
)

// AccountRepo is an autogenerated mock type for the AccountRepo type
type AccountRepo struct {
	mock.Mock
}

// AccountByUserName provides a mock function with given fields: ctx, username
func (_m *AccountRepo) AccountByUserName(ctx context.Context, username string) (*repo.Account, error) {
	ret := _m.Called(ctx, username)

	var r0 *repo.Account
	if rf, ok := ret.Get(0).(func(context.Context, string) *repo.Account); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
