apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-game-lb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}-game-lb
  replicas: {{ default 1 .Values.game_lb.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}-game-lb
    spec:
      containers:
      - name: {{ .Release.Name }}-game-lb
        image: "{{ .Values.game_lb.image.repository }}:{{ .Values.game_lb.image.tag }}"
        imagePullPolicy: {{ .Values.game_lb.image.pullPolicy | toString }}
        env:
        - name: PREFERRED_HOSTNAME
          {{- if and .Values.game_lb.hostname (ne .Values.game_lb.hostname "") }}
          value: {{ .Values.game_lb.hostname }}
          {{- else }}
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
          {{- end }}
        - name: LOG_LEVEL
          value: "0"
        - name: HEALTH_CHECK_PORT
          value: "8900"
        - name: PORT
          value: "{{ .Values.game_lb.port }}"
        - name: REDIS_URL
          value: redis://{{ .Release.Name }}-redis-headless:6379/0
        - name: NATS_URL
          value: nats://{{ .Release.Name }}-nats:4222
        - name: SERVERS_REGISTRY_SERVICE_ADDRESS
          value: {{ .Release.Name }}-servers-registry:{{ .Values.servers_registry.service.externalPort}}
        - name: CHAR_SERVICE_ADDRESS
          value: {{ .Release.Name }}-charserver:{{ .Values.charserver.service.externalPort}}
        - name: CHAT_SERVICE_ADDRESS
          value: {{ .Release.Name }}-chatserver:{{ .Values.chatserver.service.externalPort}}
        - name: GUILDS_SERVICE_ADDRESS
          value: {{ .Release.Name }}-guildserver:{{ .Values.guildserver.service.externalPort}}
        - name: MAIL_SERVICE_ADDRESS
          value: {{ .Release.Name }}-mailserver:{{ .Values.mailserver.service.externalPort}}
        - name: DB_SCHEMA_TYPE
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-databases-config
              key: schema_type
        - name: AUTH_DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-databases-config
              key: AUTH_DB_CONNECTION
        ports:
        - name: debug
          containerPort: 8333
        - name: service
          containerPort: {{ .Values.game_lb.port | int  }}
        - name: health
          containerPort: 8900
        - containerPort: 4000
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.game_lb.service.internalPort | int }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.game_lb.service.internalPort | int }}
        securityContext:
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
          # runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
{{ toYaml .Values.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-game-lb
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.game_lb.service.type }}
  ports:
  - port: {{ .Values.game_lb.port | int  }}
    targetPort: {{ .Values.game_lb.port | int  }}
    nodePort: {{ .Values.game_lb.port | int  }}
  selector:
    app: {{ $fullname }}-game-lb