apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-groupserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}-groupserver
  replicas: {{ default 1 .Values.groupserver.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}-groupserver
    spec:
      containers:
      - name: {{ .Release.Name }}-groupserver
        image: "{{ .Values.groupserver.image.repository }}:{{ .Values.groupserver.image.tag }}"
        imagePullPolicy: {{ .Values.groupserver.image.pullPolicy | toString }}
        env:
        - name: PORT
          value: "{{ .Values.groupserver.service.internalPort | int }}"
        - name: NATS_URL
          value: nats://{{ .Release.Name }}-nats:4222
        - name: CHAR_SERVICE_ADDRESS
          value: {{ .Release.Name }}-charserver:{{ .Values.charserver.service.externalPort}}
        ports:
        - containerPort: {{ .Values.groupserver.service.internalPort | int  }}
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.groupserver.service.internalPort | int }}
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: {{ .Values.groupserver.service.internalPort | int }}
        securityContext:
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
          # runAsNonRoot: true
          allowPrivilegeEscalation: false
        resources:
{{ toYaml .Values.resources | indent 10 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-groupserver
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.groupserver.service.type }}
  ports:
  - port: {{ .Values.groupserver.service.externalPort | int  }}
    targetPort: {{ .Values.groupserver.service.internalPort | int  }}
    protocol: TCP
  selector:
    app: {{ $fullname }}-groupserver