ALTER TABLE `groups`
    MODIFY leaderGuid BIGINT UNSIGNED NOT NULL,
    MODIFY looterGuid BIGINT UNSIGNED NOT NULL,
    MODIFY masterLooterGuid BIGINT UNSIGNED NOT NULL;

ALTER TABLE group_member
    MODIFY memberGuid BIGINT UNSIGNED NOT NULL,
    ADD COLUMN memberName VARCHAR(12) NOT NULL DEFAULT '' AFTER memberGuid;

ALTER TABLE group_invites
    MODIFY invited BIGINT UNSIGNED NOT NULL,
    MODIFY inviter BIGINT UNSIGNED NOT NULL,
    ADD COLUMN groupRealmId INT UNSIGNED NOT NULL DEFAULT 0 AFTER groupId;
