// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	events "github.com/walkline/ToCloud9/shared/events"
)

// LoadBalancerProducer is an autogenerated mock type for the LoadBalancerProducer type
type LoadBalancerProducer struct {
	mock.Mock
}

// CharacterLoggedIn provides a mock function with given fields: payload
func (_m *LoadBalancerProducer) CharacterLoggedIn(payload *events.LBEventCharacterLoggedInPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.LBEventCharacterLoggedInPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CharacterLoggedOut provides a mock function with given fields: payload
func (_m *LoadBalancerProducer) CharacterLoggedOut(payload *events.LBEventCharacterLoggedOutPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.LBEventCharacterLoggedOutPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CharactersUpdates provides a mock function with given fields: payload
func (_m *LoadBalancerProducer) CharactersUpdates(payload *events.LBEventCharactersUpdatesPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.LBEventCharactersUpdatesPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
