// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	events "github.com/walkline/ToCloud9/shared/events"
)

// ServerRegistryProducer is an autogenerated mock type for the ServerRegistryProducer type
type ServerRegistryProducer struct {
	mock.Mock
}

// LBAdded provides a mock function with given fields: payload
func (_m *ServerRegistryProducer) LBAdded(payload *events.ServerRegistryEventLBAddedPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.ServerRegistryEventLBAddedPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LBRemovedUnhealthy provides a mock function with given fields: payload
func (_m *ServerRegistryProducer) LBRemovedUnhealthy(payload *events.ServerRegistryEventLBRemovedUnhealthyPayload) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(*events.ServerRegistryEventLBRemovedUnhealthyPayload) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
