// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	packet "github.com/walkline/ToCloud9/apps/gateway/packet"
)

// Socket is an autogenerated mock type for the Socket type
type Socket struct {
	mock.Mock
}

// Address provides a mock function with no fields
func (_m *Socket) Address() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *Socket) Close() {
	_m.Called()
}

// ListenAndProcess provides a mock function with given fields: ctx
func (_m *Socket) ListenAndProcess(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListenAndProcess")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadChannel provides a mock function with no fields
func (_m *Socket) ReadChannel() <-chan *packet.Packet {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadChannel")
	}

	var r0 <-chan *packet.Packet
	if rf, ok := ret.Get(0).(func() <-chan *packet.Packet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *packet.Packet)
		}
	}

	return r0
}

// Send provides a mock function with given fields: _a0
func (_m *Socket) Send(_a0 *packet.Writer) {
	_m.Called(_a0)
}

// SendPacket provides a mock function with given fields: _a0
func (_m *Socket) SendPacket(_a0 *packet.Packet) {
	_m.Called(_a0)
}

// WriteChannel provides a mock function with no fields
func (_m *Socket) WriteChannel() chan<- *packet.Packet {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WriteChannel")
	}

	var r0 chan<- *packet.Packet
	if rf, ok := ret.Get(0).(func() chan<- *packet.Packet); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- *packet.Packet)
		}
	}

	return r0
}

// NewSocket creates a new instance of Socket. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocket(t interface {
	mock.TestingT
	Cleanup(func())
}) *Socket {
	mock := &Socket{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
