/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/walkline/ToCloud9/game-server/libsidecar */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "battleground-api.go"

#include "battleground-api.h"

#line 1 "cgo-generated-wrapper"

#line 3 "events-group.go"

#include "events-group.h"

#line 1 "cgo-generated-wrapper"

#line 3 "events-guilds.go"

#include "events-guild.h"

#line 1 "cgo-generated-wrapper"

#line 3 "events-servers-registry.go"

#include "events-servers-registry.h"

#line 1 "cgo-generated-wrapper"



#line 3 "guild-api.go"

#include "guild-api.h"

#line 1 "cgo-generated-wrapper"

#line 3 "lfg-api.go"

#include "lfg-api.h"

#line 1 "cgo-generated-wrapper"

#line 3 "lib.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "matchmaking.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "monitoring.go"

#include "monitoring.h"

#line 1 "cgo-generated-wrapper"

#line 3 "player-interactions-api.go"

#include "player-interactions-api.h"

#line 1 "cgo-generated-wrapper"

#line 3 "player-items-api.go"

#include "player-items-api.h"

#line 1 "cgo-generated-wrapper"

#line 3 "player-money-api.go"

#include "player-money-api.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// TC9SetBattlegroundStartHandler sets handler for starting battleground.
//
extern void TC9SetBattlegroundStartHandler(BattlegroundStartHandler h);

// TC9SetBattlegroundAddPlayersHandler sets handler for adding players to battleground.
//
extern void TC9SetBattlegroundAddPlayersHandler(BattlegroundAddPlayersHandler h);

// TC9SetCanPlayerJoinBattlegroundQueueHandler sets handler for checking if player can join to battleground queue.
//
extern void TC9SetCanPlayerJoinBattlegroundQueueHandler(CanPlayerJoinBattlegroundQueueHandler h);

// TC9SetCanPlayerTeleportToBattlegroundHandler sets handler for checking if player can teleport to battleground.
//
extern void TC9SetCanPlayerTeleportToBattlegroundHandler(CanPlayerTeleportToBattlegroundHandler h);

// TC9SetOnGroupCreatedHook sets hook for group created event.
//
extern void TC9SetOnGroupCreatedHook(OnGroupCreatedHook h);

// TC9SetOnGroupMemberAddedHook sets hook for member added event.
//
extern void TC9SetOnGroupMemberAddedHook(OnGroupMemberAddedHook h);

// TC9SetOnGroupMemberRemovedHook sets hook for member left/kicked event.
//
extern void TC9SetOnGroupMemberRemovedHook(OnGroupMemberRemovedHook h);

// TC9SetOnGroupLeaderChangedHook sets hook for leader changed event.
//
extern void TC9SetOnGroupLeaderChangedHook(OnGroupLeaderChangedHook h);

// TC9SetOnGroupDisbandedHook sets hook for group disbanded event.
//
extern void TC9SetOnGroupDisbandedHook(OnGroupDisbandedHook h);

// TC9SetOnGroupLootTypeChangedHook sets hook for group loot type changed event.
//
extern void TC9SetOnGroupLootTypeChangedHook(OnGroupLootTypeChangedHook h);

// TC9SetOnGroupDungeonDifficultyChangedHook sets hook for group dungeon difficulty changed event.
//
extern void TC9SetOnGroupDungeonDifficultyChangedHook(OnGroupDungeonDifficultyChangedHook h);

// TC9SetOnGroupRaidDifficultyChangedHook sets hook for group raid difficulty changed event.
//
extern void TC9SetOnGroupRaidDifficultyChangedHook(OnGroupRaidDifficultyChangedHook h);

// TC9SetOnGroupConvertedToRaidHook sets hook for group converted to raid event.
//
extern void TC9SetOnGroupConvertedToRaidHook(OnGroupConvertedToRaidHook h);
extern void TC9SetOnGroupReadyCheckStartedHook(OnGroupReadyCheckStartedHook h);
extern void TC9SetOnGroupReadyCheckMemberStateHook(OnGroupReadyCheckMemberStateHook h);
extern void TC9SetOnGroupReadyCheckFinishedHook(OnGroupReadyCheckFinishedHook h);
extern void TC9SetOnGroupMemberSubGroupChangedHook(OnGroupMemberSubGroupChangedHook h);
extern void TC9SetOnGroupMemberFlagsChangedHook(OnGroupMemberFlagsChangedHook h);
extern void TC9SetOnGroupMemberStateChangedHook(OnGroupMemberStateChangedHook h);
extern void TC9SetOnGroupInstanceResetRequestHook(OnGroupInstanceResetRequestHook h);
extern void TC9SetOnGroupInstanceBindExtensionRequestHook(OnGroupInstanceBindExtensionRequestHook h);
extern void TC9UpdateGroupMemberState(uint64_t memberGuid, uint8_t online, uint8_t level, uint8_t playerClass, uint32_t zoneId, uint32_t mapId, uint32_t health, uint32_t maxHealth, uint8_t powerType, uint32_t power, uint32_t maxPower, uint32_t instanceID);
extern void TC9ConfirmLfgDungeonRouteEntered(uint64_t memberGuid, uint32_t mapId, uint8_t difficulty, uint32_t instanceID);
extern void TC9StartGroupReadyCheck(uint64_t leaderGuid, uint32_t durationMs);
extern void TC9SetGroupReadyCheckMemberState(uint64_t memberGuid, uint8_t state);
extern void TC9FinishGroupReadyCheck(uint64_t playerGuid);
extern void TC9ChangeGroupMemberSubGroup(uint64_t updaterGuid, uint64_t memberGuid, uint8_t subGroup);
extern void TC9SetGroupMemberFlags(uint64_t updaterGuid, uint64_t memberGuid, uint8_t flags, uint8_t roles);
extern void TC9RegisterMaterializedLfgGroup(uint32_t groupGuid, uint64_t leaderGuid, uint8_t groupType, uint8_t difficulty, uint8_t raidDifficulty, GroupMaterializedLfgMember* members, uint8_t membersSize);

// TC9SetOnGuildMemberAddedHook sets hook for guild member added event.
//
extern void TC9SetOnGuildMemberAddedHook(OnGuildMemberAddedHook h);

// TC9SetOnGuildMemberRemovedHook sets hook for guild member removed (kicked) event.
//
extern void TC9SetOnGuildMemberRemovedHook(OnGuildMemberRemovedHook h);

// TC9SetOnGuildMemberLeftHook sets hook for guild member left event.
//
extern void TC9SetOnGuildMemberLeftHook(OnGuildMemberLeftHook h);

// TC9SetOnMapsReassignedHook sets hook for maps reassigning by servers registry event.
//
extern void TC9SetOnMapsReassignedHook(OnMapsReassignedHook h);

// TC9ProcessEventsHooks calls all events hooks.
//
extern void TC9ProcessEventsHooks();

// TC9GetNextAvailableCharacterGuid returns next available characters GUID. Thread unsafe.
//
extern GoUint64 TC9GetNextAvailableCharacterGuid(GoInt realmID);

// TC9GetNextAvailableItemGuid returns next available item GUID. Thread unsafe.
//
extern GoUint64 TC9GetNextAvailableItemGuid(GoInt realmID);

// TC9GetNextAvailableInstanceGuid returns next available dungeon/raid instance GUID. Thread unsafe.
//
extern GoUint64 TC9GetNextAvailableInstanceGuid(GoInt realmID);

// TC9SetGuildCreateHandler sets handler for creating guilds.
//
extern void TC9SetGuildCreateHandler(GuildCreateHandler h);

// TC9SetLfgPlayerLockInfoHandler sets handler for AzerothCore LFG lock info.
//
extern void TC9SetLfgPlayerLockInfoHandler(LfgPlayerLockInfoHandler h);

// TC9SetLfgPlayerInfoHandler sets handler for AzerothCore LFG player catalog and lock info.
//
extern void TC9SetLfgPlayerInfoHandler(LfgPlayerInfoHandler h);

// TC9SetLfgDungeonInfoHandler sets handler for AzerothCore LFG dungeon metadata.
//
extern void TC9SetLfgDungeonInfoHandler(LfgDungeonInfoHandler h);

// TC9SetLfgTeleportPlayerHandler sets handler for AzerothCore LFG teleport in/out.
//
extern void TC9SetLfgTeleportPlayerHandler(LfgTeleportPlayerHandler h);

// TC9SetLfgBootVoteHandler sets handler for AzerothCore LFG boot vote replies.
//
extern void TC9SetLfgBootVoteHandler(LfgBootVoteHandler h);

// TC9SetLfgMaterializeProposalHandler sets handler for AzerothCore LFG proposal materialization.
//
extern void TC9SetLfgMaterializeProposalHandler(LfgMaterializeProposalHandler h);

// TC9InitLib inits lib by starting services like grpc and healthcheck.
// Adds game server to the servers registry that will make this server visible for gateway.
//
extern void TC9InitLib(GoUint16 port, GoUint32 realmID, GoUint8 isCrossRealm, char* availableMaps, uint32_t** assignedMaps, int* assignedMapsSize);

// TC9GracefulShutdown gracefully stops all running services.
//
extern void TC9GracefulShutdown();

// TC9ProcessGRPCOrHTTPRequests calls all grpc or http handlers in queue.
//
extern void TC9ProcessGRPCOrHTTPRequests();

// TC9ReadyToAcceptPlayersFromMaps notifies servers registry that this server
// loaded maps related data and ready to accept players from those maps.
//
extern void TC9ReadyToAcceptPlayersFromMaps(uint32_t* maps, int mapsLen);

// TC9PlayerLeftBattleground notifies matchmaking server that player left battleground
//
extern void TC9PlayerLeftBattleground(uint64_t playerGUID, uint32_t realmID, uint32_t instanceID);

// TC9BattlegroundStatusChanged notifies matchmaking server that battleground status changed
//
extern void TC9BattlegroundStatusChanged(uint32_t instanceID, uint8_t status);

// TC9CompleteLfgDungeon notifies matchmaking server that AzerothCore completed an LFG dungeon.
//
extern void TC9CompleteLfgDungeon(uint32_t completedDungeonEntry, uint32_t selectedDungeonEntry, uint64_t* players, int playersSize);

// TC9SetMonitoringDataCollectorHandler sets handler for getting data to handle monitoring request.
//
extern void TC9SetMonitoringDataCollectorHandler(MonitoringDataCollectorHandler h);

// TC9SetCanPlayerInteractWithNPCAndFlagsHandler sets handler for can player interact with NPC and with given NPC flags request.
//
extern void TC9SetCanPlayerInteractWithNPCAndFlagsHandler(CanPlayerInteractWithNPCAndFlagsHandler h);

// TC9SetCanPlayerInteractWithGOAndTypeHandler sets handler for can player interact with GameObject and with given object type request.
//
extern void TC9SetCanPlayerInteractWithGOAndTypeHandler(CanPlayerInteractWithGOAndTypeHandler h);

// TC9SetGetPlayerItemsByGuidsHandler sets handler for getting players item by guids request.
//
extern void TC9SetGetPlayerItemsByGuidsHandler(GetPlayerItemsByGuidsHandler h);

// TC9SetTakePlayerItemByPosHandler sets handler for removing one player item by bag/slot.
//
extern void TC9SetTakePlayerItemByPosHandler(TakePlayerItemByPosHandler h);

// TC9SetRemoveItemsWithGuidsFromPlayerHandler sets handler for removing items by guids from player request.
//
extern void TC9SetRemoveItemsWithGuidsFromPlayerHandler(RemoveItemsWithGuidsFromPlayerHandler h);

// TC9SetAddExistingItemToPlayerHandler sets handler for adding item to player request.
//
extern void TC9SetAddExistingItemToPlayerHandler(AddExistingItemToPlayerHandler h);

// TC9SetGetMoneyForPlayerHandler sets handler for getting money for player request.
//
extern void TC9SetGetMoneyForPlayerHandler(GetMoneyForPlayerHandler h);

// TC9SetModifyMoneyForPlayerHandler sets handler for modify money for given player request.
//
extern void TC9SetModifyMoneyForPlayerHandler(ModifyMoneyForPlayerHandler h);

#ifdef __cplusplus
}
#endif
