// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	events_broadcaster "github.com/walkline/ToCloud9/apps/game-load-balancer/events-broadcaster"
)

// Broadcaster is an autogenerated mock type for the Broadcaster type
type Broadcaster struct {
	mock.Mock
}

// NewIncomingWhisperEvent provides a mock function with given fields: payload
func (_m *Broadcaster) NewIncomingWhisperEvent(payload *events_broadcaster.IncomingWhisperPayload) {
	_m.Called(payload)
}

// RegisterCharacter provides a mock function with given fields: charGUID
func (_m *Broadcaster) RegisterCharacter(charGUID uint64) <-chan events_broadcaster.Event {
	ret := _m.Called(charGUID)

	var r0 <-chan events_broadcaster.Event
	if rf, ok := ret.Get(0).(func(uint64) <-chan events_broadcaster.Event); ok {
		r0 = rf(charGUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events_broadcaster.Event)
		}
	}

	return r0
}

// UnregisterCharacter provides a mock function with given fields: charGUID
func (_m *Broadcaster) UnregisterCharacter(charGUID uint64) {
	_m.Called(charGUID)
}
